[package]
name = "linalgrs"
authors = ["Anirudh Konidala", "Aarnav Varanasi"]
version = "0.2.0"
edition = "2021"
description = "A Rust crate with Linear Algebra concept implementations from scratch!"
license = "MIT"

[dependencies]
num = "0.4.3"