[package]
name = "linalgrs"
authors = ["Anirudh Konidala", "Aarnav Varanasi", "Mariano Rodriguez"]
version = "0.3.1"
edition = "2021"
description = "A Rust crate with Linear Algebra concept implementations from scratch!"
license = "MIT"

[dependencies]
num = "0.4.3"
float-cmp = "0.10.0"